services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pimcore\Bundle\GenericDataIndexBundle\Service\Normalizer\DataObjectNormalizer: ~
    Pimcore\Bundle\GenericDataIndexBundle\Service\Normalizer\AssetNormalizer: ~